version: "3.3"
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
    networks:
      - my-net
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: page
      MYSQL_USER: page
      MYSQL_PASSWORD: page
    ports:
      - 6033:3306
    networks:
      - my-net
networks:
   my-net:
     driver: bridge
